In [92]:
import numpy as np

In [93]:
a = np.array([1,2,3])

In [94]:
print(a)

[1 2 3]


In [95]:
print(type(a))

<class 'numpy.ndarray'>


In [96]:
# 2D array
b = np.array([[1,2,3], [4,5,6]])

In [97]:
print(b)

[[1 2 3]
 [4 5 6]]


In [98]:
# 3D array
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [99]:
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [100]:
# array dtype float
d = np.array([[1,2,3], [4,5,6]], dtype=float)

In [101]:
d

array([[1., 2., 3.],
       [4., 5., 6.]])

In [102]:
# array dtype bool
e = np.array([[0,2,3], [4,5,6]], dtype=bool)

In [103]:
e

array([[False,  True,  True],
       [ True,  True,  True]])

In [104]:
# arange 
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
# arange
np.arange(1,11 , 2)

array([1, 3, 5, 7, 9])

In [106]:
# reshape 
np.arange(1,11).reshape(5, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [107]:
np.arange(1,11).reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [108]:
# ones
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [109]:
# zeros
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [110]:
# np.random will generate between 0 to 1 numbers
np.random.random((2,5))

array([[0.01655836, 0.83951942, 0.6618265 , 0.60850274, 0.75841255],
       [0.60806531, 0.59833015, 0.05124757, 0.94136718, 0.40267396]])

In [111]:
np.linspace(2 , 20 , 5)

array([ 2. ,  6.5, 11. , 15.5, 20. ])

In [112]:
np.linspace(2,10,5 ,dtype=int)

array([ 2,  4,  6,  8, 10])

In [113]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [114]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Numpy Array Attributes

In [115]:
a1 = np.arange(10)
a2 = np.arange(10 , dtype=float).reshape(5,2)
a3 = np.arange(8).reshape(4,2)

In [116]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
a2

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [118]:
a3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [119]:
# ndim
a2.ndim

2

In [120]:
a1.shape

(10,)

In [121]:
a2.shape

(5, 2)

In [122]:
a3.shape

(4, 2)

In [123]:
a1.size

10

In [124]:
a2.size

10

In [125]:
a3.shape

(4, 2)

In [126]:
a1.itemsize

4

In [127]:
a2.itemsize

8

In [128]:
a3.itemsize

4

int32 takes 4 bytes and int64 takes 64 bytes

In [129]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


## Changing dtype

In [130]:
a1.astype(np.int64)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

## Array operations

In [131]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12, 24).reshape(3,4)

In [132]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [133]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### Scalar operation

In [134]:
# arthemetic 
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [135]:
a2 + 2

array([[14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [136]:
# relational
a1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [137]:
a2 < 17

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

#### vector operation

In [138]:
# arthemtic 
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [139]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [140]:
a1 - a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

## Array functions

In [141]:
a1 = np.random.random((3,4))
a1 = np.round(a1*100)

In [142]:
a1

array([[ 7., 89., 46., 90.],
       [59., 29., 70., 10.],
       [74., 70., 56.,  9.]])

In [143]:
# max , min , sum , prod
a1.min()

7.0

In [144]:
a1.max()

90.0

In [145]:
a1.sum()

609.0

In [146]:
a1.prod()

8.06485815723168e+18

In [147]:
# finding min number in row
a1.min(axis=1) 

array([ 7., 10.,  9.])

In [148]:
# finding max number in column
a1.max(axis=0)

array([74., 89., 70., 90.])

In [149]:
# mean , median , var
a1.mean()

50.75

In [150]:
np.median(a1)

57.5

In [151]:
a1.std()

29.146540675238516

In [152]:
np.var(a1)

849.5208333333334

#### trigometric function

In [153]:
np.sin(a1)

array([[ 0.6569866 ,  0.86006941,  0.90178835,  0.89399666],
       [ 0.63673801, -0.66363388,  0.77389068, -0.54402111],
       [-0.98514626,  0.77389068, -0.521551  ,  0.41211849]])

In [154]:
np.cos(a1)

array([[ 0.75390225,  0.51017704, -0.43217794, -0.44807362],
       [-0.77108022, -0.74805753,  0.6333192 , -0.83907153],
       [ 0.17171734,  0.6333192 ,  0.85322011, -0.91113026]])

In [155]:
np.tan(a1)

array([[ 0.87144798,  1.68582537, -2.08661353, -1.99520041],
       [-0.82577401,  0.88714284,  1.22195992,  0.64836083],
       [-5.73702254,  1.22195992, -0.61127369, -0.45231566]])

In [156]:
# dot function
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12, 24).reshape(4,3)

In [157]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [158]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [159]:
np.dot(a2, a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [160]:
# log and exponents
np.log(a1)

array([[1.94591015, 4.48863637, 3.8286414 , 4.49980967],
       [4.07753744, 3.36729583, 4.24849524, 2.30258509],
       [4.30406509, 4.24849524, 4.02535169, 2.19722458]])

In [161]:
np.exp(a1)

array([[1.09663316e+03, 4.48961282e+38, 9.49611942e+19, 1.22040329e+39],
       [4.20121040e+25, 3.93133430e+12, 2.51543867e+30, 2.20264658e+04],
       [1.37338298e+32, 2.51543867e+30, 2.09165950e+24, 8.10308393e+03]])

In [162]:
# round , floor , ceil
np.random.random((3, 4))*100

array([[16.63331554, 44.82745675,  4.17588305, 15.36949238],
       [83.73281189, 56.49862064, 83.2280988 , 24.48096202],
       [64.4412154 , 28.02008629, 15.08614458, 64.30277941]])

In [163]:
np.round(np.random.random((3, 4))*100)

array([[57., 95., 70., 49.],
       [34., 82., 65., 15.],
       [40., 51., 10., 98.]])

In [164]:
np.floor(np.random.random((3, 4))*100)

array([[99., 79., 33., 51.],
       [30., 77., 81., 71.],
       [67., 97., 53., 87.]])

In [165]:
np.ceil(np.random.random((3, 4))*100)

array([[69., 22., 45., 26.],
       [20.,  5., 37., 36.],
       [44., 96., 80., 36.]])

## indexing and slicing

#### indexing

In [166]:
a1 = np.arange(12)
a2 = np.arange(12, 24).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [167]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [168]:
a1[-1]

11

In [169]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [170]:
# find 18
a2[1,2]

18

In [171]:
# find 23
a2[2,3]

23

In [172]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [173]:
# finding 5
a3[1, 0 , 1]

5

In [174]:
# finding 6
a3[1,1,0]

6

In [175]:
# finding 2
a3[0, 1,0]

2

In [176]:
# finding 0
a3[0,0,0]

0

#### slicing

In [177]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [178]:

a1[2:7]

array([2, 3, 4, 5, 6])

In [179]:
a1[2:7:2]

array([2, 4, 6])

In [183]:
 a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [181]:
a2[0:1]

array([[12, 13, 14, 15]])

In [182]:
a2[1:-1]

array([[16, 17, 18, 19]])

In [184]:
# finding 17 ,18 and 21 ,22
a2[1:,1:3]

array([[17, 18],
       [21, 22]])

In [185]:
a2[1:,2:]

array([[18, 19],
       [22, 23]])

In [191]:
a2[::2,::3]

array([[12, 15],
       [20, 23]])

In [210]:
a2[:3:2,1::2]

array([[13, 15],
       [21, 23]])

In [212]:
a2[1,::3]

array([16, 19])

In [214]:
a3 = np.arange(27).reshape(3,3,3)

In [215]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [216]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [221]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [229]:
a3[0,1]

array([3, 4, 5])

In [238]:
a3[1,:,1]

array([10, 13, 16])

In [240]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [269]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

## Iterating

In [274]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [275]:
a2
for i in a2:
    print(i)

[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [272]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [276]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [277]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshape

In [278]:
# transpose
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [279]:
a2.transpose()

array([[12, 16, 20],
       [13, 17, 21],
       [14, 18, 22],
       [15, 19, 23]])

In [280]:
# ravel
a2.ravel()

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [281]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## stacking

In [283]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [284]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [285]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [286]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## splitting

In [287]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [288]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [289]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [293]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]